In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import torch

In [3]:
from loss_cal.costs import RevGaussCost, StepCost_weighted
from loss_cal.actions import UniformAction, CategoricalAction

In [28]:
cost_fn1 = RevGaussCost(parameter_range=10)
cost_fn2 = StepCost_weighted([1,2], threshold=0.5)

In [29]:
th = torch.arange(3).unsqueeze(1)
acs = torch.zeros((3)).unsqueeze(1)

In [3]:
UniformAction(0,5).sample(2).shape, CategoricalAction(2, None).sample(2).shape

(torch.Size([2, 1]), torch.Size([2, 1]))

In [24]:
cost_fn1(th, acs)

tensor([[0.0000],
        [0.8946],
        [1.0000]])

In [13]:
cost_fn2(th, acs)

tensor([[0.],
        [1.],
        [1.]])

In [14]:
from loss_cal.tasks.task import BenchmarkTask


In [20]:
sir = BenchmarkTask(name="sir", action_type="binary")

sir.prior_params

{'loc': tensor([-0.9163, -2.0794]), 'scale': tensor([0.5000, 0.2000])}

In [13]:
class SIR(BenchmarkTask):
    def __init__(self, action_type: str) -> None:
        super().__init__("sir", action_type)

(tensor([[0.5319, 0.1150],
         [0.5836, 0.0999],
         [0.9488, 0.1182],
         [0.4671, 0.0999],
         [0.6658, 0.0931],
         [0.6905, 0.1102],
         [0.4813, 0.1004],
         [0.5772, 0.1780],
         [0.5179, 0.1295],
         [0.2862, 0.1780]]),
 tensor([[  0.,   1., 404., 148.,  27.,   0.,   0.,   0.,   0.,   0.],
         [  0.,   3., 515., 112.,  19.,   4.,   0.,   0.,   0.,   0.],
         [  0., 496., 123.,  24.,   3.,   0.,   0.,   0.,   0.,   0.],
         [  0.,   1., 207., 294.,  62.,  13.,   2.,   0.,   0.,   1.],
         [  0.,  16., 401.,  79.,  20.,   6.,   0.,   1.,   0.,   0.],
         [  0.,  13., 357.,  50.,   9.,   0.,   0.,   0.,   0.,   0.],
         [  0.,   1., 243., 269.,  58.,   8.,   2.,   0.,   0.,   0.],
         [  0.,   0., 282.,  64.,   7.,   0.,   1.,   0.,   0.,   0.],
         [  0.,   0., 266., 158.,  17.,   3.,   1.,   0.,   0.,   0.],
         [  0.,   0.,   0.,   0.,   2.,   7.,  28.,  71.,  49.,  21.]]),
 tensor([[0.2942

In [35]:
for pname, pval in zip(sir.parameter_names, sir.get_true_parameters(n=1).T):
    print(rf"{pname}={pval}")

$\beta$=tensor([0.6148])
$\gamma$=tensor([0.1917])


['$\\beta$', '$\\gamma$']

In [32]:
sir._task.get_labels_parameters()[0]

'$\\beta$'

'$\\beta$=0.6148 $\\gamma$=0.1917'

In [ ]:
torch.distributions.LogNormal().icdf()